--- ../../pikeyd/Makefile	2021-04-28 11:14:37.806338285 -0400
+++ Makefile	2021-04-14 06:56:38.346567202 -0400
@@ -1,7 +1,7 @@
-TARGET:=pikeyd
+TARGET:=pikeyd165
 
 #comment out the line below when _NOT_ cross compiling
-include crosscomp.rules
+#include crosscomp.rules
 
 ifneq ($(CROSS), yes)
 CC := gcc
@@ -10,17 +10,24 @@
 endif
 
 CFLAGS=-O2 -Wstrict-prototypes -Wmissing-prototypes $(INCLUDE)
+CFLAGS=-O3 -funroll-loops -Wstrict-prototypes -Wmissing-prototypes $(INCLUDE)
 SRC := $(wildcard *.c)
 OBJ := $(patsubst %.c,%.o,$(SRC))
-LIBS=
+LIBS=-lbcm2835
+
+
+#get build dir and date
+SHELL := /bin/bash
+VPATH := $(shell basename `pwd`)
+VDATE := $(shell date)
 
 all: $(TARGET)
 
 $(TARGET): $(OBJ)
-	$(CC) -s $(OBJ) -o $@ $(LDFLAGS) $(LIBS)
+	$(CC) -DBVERSION='"$(VPATH)"' -DBDATE='"$(VDATE)"' -s $(OBJ) -o $@ $(LDFLAGS) $(LIBS)
 
 %.o: %.c
-	$(CC) $(CFLAGS) -c $< -o $@
+	$(CC) -DBVERSION='"$(VPATH)"' -DBDATE='"$(VDATE)"'  $(CFLAGS) -c $< -o $@
 
 clean:
 	rm -f $(TARGET) *.o *~
